generated
scopes
	^ OrderedCollection withAll: #(
		'https://www.googleapis.com/auth/drive.metadata'
		'https://www.googleapis.com/auth/drive.file'
		'https://www.googleapis.com/auth/drive'
		'https://www.googleapis.com/auth/drive.apps.readonly'
		'https://www.googleapis.com/auth/drive.meet.readonly'
		'https://www.googleapis.com/auth/drive.appdata'
		'https://www.googleapis.com/auth/drive.scripts'
		'https://www.googleapis.com/auth/drive.photos.readonly'
		'https://www.googleapis.com/auth/drive.readonly'
		'https://www.googleapis.com/auth/drive.metadata.readonly'
	)
